name: Download, Patch & Recompile APK

on:
  push:
    branches:
      - main        # or replace with your default branch
  workflow_dispatch:  # still allow manual runs

jobs:
  patch-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install apkeep
        run: |
          sudo apt-get update
          sudo apt-get install -y cargo
          cargo install apkeep

      - name: Download APK
        run: |
          mkdir -p downloads
          apkeep -a com.sega.ColorfulStage.en -d apk-pure downloads

      - name: Install apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.0.jar -O apktool.jar
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      - name: Decompile APK
        run: |
          apktool d downloads/com.sega.ColorfulStage.en.apk -o decompiled

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine wine32 wine64 winbind

      - name: Patch libil2cpp.so
        working-directory: decompiled/lib/arm64-v8a
        run: |
          curl -L -o ProjectSekai.exe \
            https://github.com/felzard/patch/releases/download/1/ProjectSekai.exe
          wine ProjectSekai.exe libil2cpp.so
          rm libil2cpp.so ProjectSekai.exe
          mv libil2cpp_patched.so libil2cpp.so

      - name: Recompile APK (unsigned)
        run: |
          apktool b decompiled -o patched-unsigned.apk

      - name: Generate debug keystore
        run: |
          keytool -genkey -v \
            -keystore debug.keystore \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Sign APK (v1)
        run: |
          jarsigner \
            -verbose \
            -sigalg SHA1withRSA \
            -digestalg SHA1 \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            patched-unsigned.apk \
            androiddebugkey

      - name: Align APK
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign
          zipalign -v -p 4 patched-unsigned.apk patched-signed.apk

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProjectSekai-Patched-APK
          path: |
            patched-unsigned.apk
            patched-signed.apk
