name: Download, Patch & Recompile APK

on:
  push:
    branches:
      - main        # or replace with your default branch
  workflow_dispatch:  # manual trigger

jobs:
  patch-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install apkeep
        run: |
          sudo apt-get update
          sudo apt-get install -y cargo
          cargo install apkeep

      - name: Download APK/XAPK from APKPure
        run: |
          mkdir -p downloads
          apkeep -a com.sega.ColorfulStage.en -d apk-pure downloads

      - name: Install apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.0.jar -O apktool.jar
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine wine32 wine64 winbind

      - name: Process and Decompile APK/XAPK
        run: |
          set -e

          FILE=$(ls downloads/*.{apk,xapk} 2>/dev/null | head -n1)
          if [ -z "$FILE" ]; then
            echo "❌ No .apk or .xapk found"; exit 1
          fi

          WORKDIR=$(pwd)

          if [[ "$FILE" == *.xapk ]]; then
            echo "📦 Detected XAPK, extracting..."
            TMPDIR=$(mktemp -d)
            unzip -q "$FILE" -d "$TMPDIR"

            BASEAPK=$(find "$TMPDIR" -name "*base.apk" | head -n1)
            CONFIGAPK=$(find "$TMPDIR" -name "*config.arm64_v8a.apk" | head -n1)

            if [ -z "$BASEAPK" ] || [ -z "$CONFIGAPK" ]; then
              echo "❌ Missing split APKs inside .xapk"; exit 1
            fi

            echo "🧩 Merging split APKs..."
            mkdir merge_apk
            cp "$BASEAPK" merge_apk/base.apk
            cp "$CONFIGAPK" merge_apk/config.apk
            cd merge_apk
            zip -u merged.apk base.apk config.apk
            cd "$WORKDIR"
            mv merge_apk/merged.apk downloads/merged.apk

            APK="downloads/merged.apk"
          else
            APK="$FILE"
          fi

          echo "📥 Using APK: $APK"
          apktool d "$APK" -o decompiled

      - name: Upload merged APK (if from XAPK)
        if: success() && hashFiles('downloads/merged.apk') != ''
        uses: actions/upload-artifact@v4
        with:
          name: Merged-APK
          path: downloads/merged.apk

      - name: Patch libil2cpp.so
        working-directory: decompiled/lib/arm64-v8a
        run: |
          curl -L -o ProjectSekai.exe https://github.com/felzard/patch/releases/download/1/ProjectSekai.exe
          wine ProjectSekai.exe libil2cpp.so
          rm libil2cpp.so ProjectSekai.exe
          mv libil2cpp_patched.so libil2cpp.so

      - name: Rebuild unsigned APK
        run: |
          apktool b decompiled -o patched-unsigned.apk

      - name: Generate debug keystore
        run: |
          keytool -genkey -v \
            -keystore debug.keystore \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Sign APK with debug keystore
        run: |
          jarsigner \
            -verbose \
            -sigalg SHA1withRSA \
            -digestalg SHA1 \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            patched-unsigned.apk \
            androiddebugkey

      - name: Align signed APK
        run: |
          ZIPALIGN=$(find /usr -name zipalign | head -n 1)
          $ZIPALIGN -v -p 4 patched-unsigned.apk patched-signed.apk

      - name: Upload Final APKs
        uses: actions/upload-artifact@v4
        with:
          name: ProjectSekai-Patched-APK
          path: |
            patched-unsigned.apk
            patched-signed.apk
